import { Injectable } from '@angular/core';
import * as XLSX from 'xlsx';

export interface ExcelColumn<T> {
  /** Display name in the header row. */
  header: string;
  /** Function that extracts the cell value for a row. */
  value: (row: T) => string | number | boolean | Date | null | undefined;
  /** Column width in characters. Defaults to 20. */
  width?: number;
}

export interface ExcelExportOptions {
  /** Filename without extension; current timestamp is appended automatically. */
  filename: string;
  /** Sheet tab name (≤31 chars). Defaults to "Sheet1". */
  sheetName?: string;
  /** Include a timestamp footer row at the bottom. Defaults to true. */
  includeFooter?: boolean;
}

/**
 * Generates an .xlsx workbook from any tabular data and triggers a browser download.
 *
 * Example:
 *   excel.export(users, [
 *     { header: 'Name',  value: u => u.name,  width: 30 },
 *     { header: 'Email', value: u => u.email, width: 35 },
 *   ], { filename: 'users', sheetName: 'Users' });
 */
@Injectable({ providedIn: 'root' })
export class ExcelExportService {
  export<T>(rows: T[], columns: ExcelColumn<T>[], options: ExcelExportOptions): void {
    const headerRow = columns.map((c) => c.header);
    const dataRows = rows.map((row) =>
      columns.map((c) => {
        const v = c.value(row);
        return v === null || v === undefined ? '' : v;
      })
    );

    const aoa: (string | number | boolean | Date)[][] = [headerRow, ...dataRows];

    if (options.includeFooter !== false) {
      aoa.push([]);
      aoa.push([`Generated by LEVO · ${new Date().toLocaleString()}`]);
    }

    const worksheet = XLSX.utils.aoa_to_sheet(aoa);

    worksheet['!cols'] = columns.map((c) => ({ wch: c.width ?? 20 }));

    worksheet['!autofilter'] = {
      ref: XLSX.utils.encode_range({
        s: { r: 0, c: 0 },
        e: { r: rows.length, c: columns.length - 1 }
      })
    };

    worksheet['!freeze'] = { ySplit: 1 };

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      workbook,
      worksheet,
      this.safeSheetName(options.sheetName ?? 'Sheet1')
    );

    const filename = `${options.filename}-${this.timestamp()}.xlsx`;
    XLSX.writeFile(workbook, filename);
  }

  private timestamp(): string {
    const d = new Date();
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`;
  }

  /** Excel sheet names are limited to 31 chars and cannot contain : \ / ? * [ ]. */
  private safeSheetName(raw: string): string {
    return raw.replace(/[:\\/?*\[\]]/g, ' ').slice(0, 31) || 'Sheet1';
  }
}
