import { Component, computed, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { map } from 'rxjs';

import { AuthService } from '../../core/auth/auth.service';
import { PermissionsService } from '../../core/services/permissions.service';

interface AiInsight {
  icon: 'flag' | 'savings' | 'trend';
  title: string;
  body: string;
}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="page">
      @if (forbiddenModule()) {
        <div class="banner banner-warn">
          <strong>Access denied</strong>
          You don't have permission to view <code>{{ forbiddenModule() }}</code>.
          Ask an administrator to grant you access.
        </div>
      }

      <!-- Hero -->
      <section class="hero">
        <div class="hero-text">
          <span class="eyebrow">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
              <path d="M12 2 L13.8 8.2 L20 10 L13.8 11.8 L12 18 L10.2 11.8 L4 10 L10.2 8.2 Z"/>
            </svg>
            AI-Powered Dashboard
          </span>
          <h1>
            Welcome back@if (auth.currentUser(); as user) {, <span class="hero-name">{{ user.name.split(' ')[0] }}</span>}.
          </h1>
          <p>Your AI agents are standing by — here's a snapshot of your account and what you can access today.</p>
        </div>
        <div class="hero-illu" aria-hidden="true">
          <svg viewBox="0 0 220 150" fill="none" xmlns="http://www.w3.org/2000/svg">
            <rect x="20" y="84" width="180" height="46" rx="10" fill="rgba(255,255,255,0.18)" stroke="rgba(255,255,255,0.4)"/>
            <rect x="32" y="96" width="120" height="6" rx="3" fill="rgba(255,255,255,0.6)"/>
            <rect x="32" y="110" width="80" height="6" rx="3" fill="rgba(255,255,255,0.4)"/>
            <circle cx="170" cy="64" r="38" fill="rgba(255,255,255,0.22)" stroke="rgba(255,255,255,0.45)"/>
            <g transform="translate(170,64)">
              <path d="M 0 -16 L 3.2 -3.2 L 16 0 L 3.2 3.2 L 0 16 L -3.2 3.2 L -16 0 L -3.2 -3.2 Z" fill="#ffffff"/>
            </g>
            <circle cx="195" cy="32" r="3" fill="#ffffff"/>
            <circle cx="146" cy="38" r="2" fill="#ffffff" opacity="0.7"/>
            <circle cx="200" cy="100" r="2.4" fill="#ffffff" opacity="0.7"/>
          </svg>
        </div>
      </section>

      <!-- Stats -->
      <section class="stats">
        <div class="stat-card">
          <div class="stat-icon stat-icon--blue">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
              <polyline points="14 2 14 8 20 8"></polyline>
            </svg>
          </div>
          <div>
            <span class="stat-label">Modules accessible</span>
            <span class="stat-value">{{ accessibleModules() }}</span>
          </div>
        </div>

        <div class="stat-card">
          <div class="stat-icon stat-icon--cyan">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M20 6L9 17l-5-5"></path>
            </svg>
          </div>
          <div>
            <span class="stat-label">Total permissions</span>
            <span class="stat-value">{{ totalPermissions() }}</span>
          </div>
        </div>

        <div class="stat-card stat-card--ai">
          <div class="stat-icon stat-icon--ai">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 2 L13.8 8.2 L20 10 L13.8 11.8 L12 18 L10.2 11.8 L4 10 L10.2 8.2 Z"/>
            </svg>
          </div>
          <div>
            <span class="stat-label">AI Engine</span>
            <span class="stat-value">
              Active
              <span class="live-dot"></span>
            </span>
          </div>
        </div>
      </section>

      <!-- AI Insights -->
      <section class="ai-insights">
        <div class="ai-insights__header">
          <div class="ai-insights__title">
            <span class="ai-mark">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path d="M12 2 L13.8 8.2 L20 10 L13.8 11.8 L12 18 L10.2 11.8 L4 10 L10.2 8.2 Z"/>
              </svg>
            </span>
            <div>
              <h3>AI Insights</h3>
              <small>Generated by LEVO AI · Updates as new data arrives</small>
            </div>
          </div>
          <span class="pill pill--ai">Beta</span>
        </div>

        <ul class="insight-list">
          @for (item of insights; track item.title) {
            <li class="insight">
              <span class="insight-icon" [attr.data-kind]="item.icon" [innerHTML]="insightIcon(item.icon)"></span>
              <div>
                <strong>{{ item.title }}</strong>
                <span>{{ item.body }}</span>
              </div>
            </li>
          }
        </ul>
      </section>

      <!-- Profile + Permissions -->
      <section class="grid">
        <div class="card profile-card">
          <div class="card-header">
            <h3>Account details</h3>
            <span class="pill">JWT</span>
          </div>
          @if (auth.currentUser(); as user) {
            <div class="profile">
              <div class="avatar avatar--lg">{{ initials() }}</div>
              <div class="profile-meta">
                <strong>{{ user.name }}</strong>
                <span>{{ user.email }}</span>
                <span class="role-tag">{{ user.role }}</span>
              </div>
            </div>
          }
        </div>

        <div class="card permissions-card">
          <div class="card-header">
            <h3>Module access</h3>
            <span class="pill pill--muted">{{ permissions().length }} modules</span>
          </div>

          @if (permissions().length === 0) {
            <p class="empty">No module permissions assigned yet.</p>
          } @else {
            <ul class="perm-list">
              @for (p of permissions(); track p.moduleCode) {
                <li class="perm-row">
                  <div class="perm-info">
                    <strong>{{ p.moduleName }}</strong>
                    <span class="perm-code">{{ p.moduleCode }}</span>
                  </div>
                  <div class="perm-flags">
                    <span class="flag" [class.on]="p.canView">View</span>
                    <span class="flag" [class.on]="p.canCreate">Create</span>
                    <span class="flag" [class.on]="p.canEdit">Edit</span>
                    <span class="flag" [class.on]="p.canDelete">Delete</span>
                  </div>
                </li>
              }
            </ul>
          }
        </div>
      </section>
    </section>
  `,
  styles: [`
    :host { display: block; }

    .page { display: flex; flex-direction: column; gap: 22px; }

    .banner {
      padding: 12px 16px;
      border-radius: var(--radius-md);
      font-size: 13px;
      strong { display: block; margin-bottom: 2px; font-size: 13.5px; }
      code { background: rgba(0,0,0,0.06); padding: 1px 6px; border-radius: 4px; font-size: 12px; }
    }
    .banner-warn {
      background: #fef9c3;
      color: #854d0e;
      border: 1px solid #fde68a;
    }

    .hero {
      display: flex; gap: 24px; align-items: center; justify-content: space-between;
      padding: 28px 30px;
      border-radius: var(--radius-lg);
      background: var(--gradient-brand);
      color: #fff;
      position: relative; overflow: hidden;
      box-shadow: var(--shadow-md);
    }
    .hero::after {
      content: ""; position: absolute;
      width: 320px; height: 320px; border-radius: 50%;
      top: -160px; right: -120px;
      background: radial-gradient(circle, rgba(255,255,255,0.25) 0%, transparent 70%);
      pointer-events: none;
    }
    .hero-text { position: relative; z-index: 1; }
    .eyebrow {
      display: inline-flex; align-items: center; gap: 6px;
      font-size: 11px; font-weight: 700; letter-spacing: 0.6px; text-transform: uppercase;
      background: rgba(255,255,255,0.18);
      padding: 5px 12px; border-radius: 999px;
      margin-bottom: 10px;
      backdrop-filter: blur(6px);
    }
    .eyebrow svg { animation: sparkle 2.6s ease-in-out infinite; }
    @keyframes sparkle {
      0%, 100% { transform: rotate(0deg) scale(1); }
      50%      { transform: rotate(15deg) scale(1.18); }
    }
    .hero h1 { margin: 0 0 6px; font-size: 26px; font-weight: 700; letter-spacing: -0.4px; }
    .hero-name { color: #fff; }
    .hero p { margin: 0; color: rgba(255,255,255,0.92); font-size: 14px; }
    .hero-illu { width: 220px; height: 150px; flex-shrink: 0; opacity: 0.95; position: relative; z-index: 1; }
    .hero-illu svg { width: 100%; height: 100%; }

    .stats {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 14px;
    }
    .stat-card {
      background: var(--color-surface);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-lg);
      padding: 18px 18px;
      display: flex; align-items: center; gap: 14px;
      box-shadow: var(--shadow-xs);
      transition: transform 0.2s var(--ease-out), box-shadow 0.2s var(--ease-out);
    }
    .stat-card:hover { transform: translateY(-2px); box-shadow: var(--shadow-md); }
    .stat-icon {
      width: 44px; height: 44px; border-radius: 12px;
      display: flex; align-items: center; justify-content: center;
      flex-shrink: 0;
    }
    .stat-icon--blue { background: var(--color-primary-100); color: var(--color-primary-700); }
    .stat-icon--cyan { background: #cffafe; color: #0e7490; }
    .stat-icon--ai   { background: var(--gradient-brand); color: #fff; }

    .stat-card--ai {
      background: linear-gradient(135deg, #ffffff, #f0f9ff);
      border-color: var(--color-primary-200);
    }
    .live-dot {
      display: inline-block;
      width: 8px; height: 8px; border-radius: 50%;
      background: #10b981;
      margin-left: 8px;
      box-shadow: 0 0 0 0 rgba(16, 185, 129, 0.55);
      animation: pulseDot 2s ease-out infinite;
      vertical-align: middle;
    }
    @keyframes pulseDot {
      0%   { box-shadow: 0 0 0 0 rgba(16, 185, 129, 0.55); }
      80%  { box-shadow: 0 0 0 8px rgba(16, 185, 129, 0); }
      100% { box-shadow: 0 0 0 0 rgba(16, 185, 129, 0); }
    }

    .stat-label { display: block; font-size: 12px; color: var(--color-text-muted); font-weight: 500; }
    .stat-value { display: block; font-size: 22px; color: var(--color-text); font-weight: 700; letter-spacing: -0.3px; }

    .ai-insights {
      background: var(--color-surface);
      border: 1px solid var(--color-primary-100);
      border-radius: var(--radius-lg);
      padding: 22px 24px;
      box-shadow: var(--shadow-xs);
      position: relative; overflow: hidden;
    }
    .ai-insights::before {
      content: ""; position: absolute; top: 0; left: 0; right: 0; height: 3px;
      background: var(--gradient-brand);
    }
    .ai-insights__header {
      display: flex; align-items: center; justify-content: space-between;
      margin-bottom: 16px;
    }
    .ai-insights__title { display: flex; align-items: center; gap: 12px;
      h3 { margin: 0; font-size: 16px; font-weight: 700; color: var(--color-text); }
      small { color: var(--color-text-muted); font-size: 11.5px; }
    }
    .ai-mark {
      width: 36px; height: 36px;
      border-radius: 10px;
      background: var(--gradient-brand);
      color: #fff;
      display: inline-flex; align-items: center; justify-content: center;
      box-shadow: 0 4px 12px rgba(59, 130, 246, 0.32);
    }
    .ai-mark svg { animation: sparkle 2.6s ease-in-out infinite; }

    .pill {
      font-size: 11px; font-weight: 600; padding: 3px 10px; border-radius: 999px;
      background: var(--color-primary-100); color: var(--color-primary-700);
      letter-spacing: 0.4px;
    }
    .pill--muted { background: var(--color-surface-2); color: var(--color-text-muted); border: 1px solid var(--color-border); }
    .pill--ai { background: var(--gradient-brand); color: #fff; border: none; }

    .insight-list {
      list-style: none; padding: 0; margin: 0;
      display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
      gap: 12px;
    }
    .insight {
      display: flex; align-items: flex-start; gap: 12px;
      padding: 14px;
      background: linear-gradient(135deg, var(--color-surface-2), #f0f9ff);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-md);
      transition: border-color 0.15s var(--ease-out), transform 0.15s var(--ease-out);

      strong { display: block; font-size: 13.5px; color: var(--color-text); margin-bottom: 3px; }
      span   { display: block; font-size: 12.5px; color: var(--color-text-muted); line-height: 1.45; }
    }
    .insight:hover { border-color: var(--color-primary-300); transform: translateY(-1px); }
    .insight-icon {
      width: 32px; height: 32px; border-radius: 9px;
      display: inline-flex; align-items: center; justify-content: center;
      flex-shrink: 0;
    }
    .insight-icon[data-kind="flag"]    { background: #fef3c7; color: #b45309; }
    .insight-icon[data-kind="savings"] { background: #d1fae5; color: #047857; }
    .insight-icon[data-kind="trend"]   { background: var(--color-primary-100); color: var(--color-primary-700); }

    .grid {
      display: grid;
      grid-template-columns: minmax(280px, 360px) 1fr;
      gap: 18px;
    }
    .card {
      background: var(--color-surface);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-lg);
      padding: 20px 22px;
      box-shadow: var(--shadow-xs);
    }
    .card-header {
      display: flex; align-items: center; justify-content: space-between;
      margin-bottom: 14px;
      h3 { margin: 0; font-size: 15px; font-weight: 600; color: var(--color-text); }
    }

    .avatar {
      width: 38px; height: 38px;
      border-radius: 50%;
      background: var(--gradient-brand);
      color: #fff;
      display: flex; align-items: center; justify-content: center;
      font-size: 13px; font-weight: 600;
      box-shadow: 0 4px 10px rgba(59, 130, 246, 0.3);
    }
    .avatar--lg { width: 56px; height: 56px; font-size: 18px; }

    .profile { display: flex; align-items: center; gap: 14px; }
    .profile-meta { display: flex; flex-direction: column; gap: 2px; }
    .profile-meta strong { font-size: 15px; color: var(--color-text); }
    .profile-meta span { font-size: 13px; color: var(--color-text-muted); }
    .role-tag {
      align-self: flex-start;
      margin-top: 4px;
      font-size: 11px !important;
      font-weight: 600;
      padding: 3px 8px;
      border-radius: 999px;
      background: var(--color-primary-50);
      color: var(--color-primary-700) !important;
      border: 1px solid var(--color-primary-100);
    }

    .empty {
      margin: 0; padding: 24px;
      color: var(--color-text-muted); font-size: 13px;
      text-align: center;
      background: var(--color-surface-2);
      border-radius: var(--radius-md);
    }
    .perm-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 8px; }
    .perm-row {
      display: flex; align-items: center; justify-content: space-between;
      gap: 12px;
      padding: 12px 14px;
      border-radius: var(--radius-md);
      background: var(--color-surface-2);
      border: 1px solid var(--color-border);
      transition: border-color 0.15s var(--ease-out), background 0.15s var(--ease-out);
    }
    .perm-row:hover { border-color: var(--color-primary-300); background: #fff; }
    .perm-info { display: flex; flex-direction: column; gap: 2px; min-width: 0; }
    .perm-info strong { font-size: 13.5px; color: var(--color-text); font-weight: 600; }
    .perm-code { font-size: 11px; color: var(--color-text-subtle); letter-spacing: 0.3px; text-transform: uppercase; }
    .perm-flags { display: flex; gap: 6px; flex-wrap: wrap; justify-content: flex-end; }
    .flag {
      font-size: 11px; font-weight: 600; padding: 4px 8px;
      border-radius: 999px;
      background: #f3f4f6; color: #9ca3af; border: 1px solid #e5e7eb;
      letter-spacing: 0.3px;
    }
    .flag.on {
      background: var(--color-primary-100); color: var(--color-primary-700); border-color: var(--color-primary-200);
    }

    @media (max-width: 980px) {
      .grid { grid-template-columns: 1fr; }
      .hero-illu { display: none; }
    }
    @media (max-width: 640px) {
      .hero { padding: 22px; }
      .hero h1 { font-size: 22px; }
      .perm-row { flex-direction: column; align-items: flex-start; }
      .perm-flags { justify-content: flex-start; }
    }
  `]
})
export class DashboardComponent {
  readonly auth = inject(AuthService);
  private readonly perms = inject(PermissionsService);
  private readonly route = inject(ActivatedRoute);

  readonly permissions = this.perms.permissions;

  readonly forbiddenModule = toSignal(
    this.route.queryParamMap.pipe(map((p) => p.get('forbidden'))),
    { initialValue: null as string | null }
  );

  readonly accessibleModules = computed(() =>
    this.permissions().filter((p) => p.canView).length
  );

  readonly totalPermissions = computed(() =>
    this.permissions().reduce((sum, p) =>
      sum + (p.canView ? 1 : 0) + (p.canCreate ? 1 : 0) + (p.canEdit ? 1 : 0) + (p.canDelete ? 1 : 0), 0)
  );

  readonly initials = computed(() => {
    const u = this.auth.currentUser();
    if (!u) return '';
    const parts = u.name.trim().split(/\s+/);
    const first = parts[0]?.[0] ?? '';
    const last = parts.length > 1 ? parts[parts.length - 1][0] : '';
    return (first + last).toUpperCase() || u.email[0].toUpperCase();
  });

  readonly insights: AiInsight[] = [
    { icon: 'flag',    title: 'Anomaly detection',      body: 'AI agents are watching every invoice for duplicate charges, rate mismatches, and weight anomalies.' },
    { icon: 'savings', title: 'Savings opportunities',  body: 'Once your carrier feed is connected, AI will surface dispute candidates and recovery suggestions.' },
    { icon: 'trend',   title: 'Carrier intelligence',   body: 'Predictive scoring on on-time performance, accessorial trends, and lane-level cost outliers.' }
  ];

  insightIcon(kind: AiInsight['icon']): string {
    const stroke = `stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"`;
    switch (kind) {
      case 'flag':    return `<svg width="16" height="16" viewBox="0 0 24 24" ${stroke}><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" y1="22" x2="4" y2="15"/></svg>`;
      case 'savings': return `<svg width="16" height="16" viewBox="0 0 24 24" ${stroke}><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>`;
      case 'trend':   return `<svg width="16" height="16" viewBox="0 0 24 24" ${stroke}><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>`;
    }
  }
}
